
import "./globals.css";
import Navbar from './components/Home/Navbar';
import Footer from './components/Home/Footer';
import Loading from './components/Home/Loading';





export const metadata = {
  title: "Agrsco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="ar" dir="rtl">
      <body>
   
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
